version: '3.9'


services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "LangStorm"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
#      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  server:
    image: langstorm-backend
    environment:
      DB_HOST: "db"
    build:
      context: ../src/server/
      dockerfile: ../../docker/backend/Dockerfile
    ports:
      - 9090:8080
    depends_on:
      - db

  app:
    image: langstorm-frontend
    build:
      context: ../src/frontend/
      dockerfile: ../../docker/frontend/Dockerfile
    ports:
      - 7000:3000
    depends_on:
      - server

volumes:
  postgres_data: